### ISSUE TITLE
Twitter Promise error

### ISSUE THREAD

**Issue by CapitanRedBeard** [AppAndFlow/exponent-twitter-login-example#1]
Loading up app in XDE and pressing the 'Login with Twitter' causes a unhandled promise error.

**Comment by janicduplessis** [comment]
Did you also start the web server in twitter-login-backend? We should probably add some error handling.

**Comment by CapitanRedBeard** [comment]
Derp. My bad, totally glossed over that.
I'm noticing the web browser is having trouble communicating back to expo tho. The expo app crashes after authenticating on the web browser. At least on an iOS simulator. Do I need to be on a physical device to get the full handshake to work?

**Comment by janicduplessis** [comment]
Strange, it should work on iOS simulator, will test tomorrow.
